#!/usr/bin/env bash
# Phase-1 validation for the native macOS shell.
#
# Default mode checks everything that can be checked without leaving a long-lived
# app process running:
#   - Python brain sidecar transport test
#   - Swift package tests
#   - Swift package build
#
# Pass --run to launch the Wisp executable with terminal-attached logs after
# those checks. Pass --open to launch the generated Wisp.app bundle the way
# Finder does, without the shell-provided brain/log environment.
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_DIR="$REPO_ROOT/build_logs/macos_phase1_$RUN_ID"
ARCHIVE_PATH="$REPO_ROOT/build_logs/wisp-macos-logs_$RUN_ID.zip"
SUMMARY_LOG="$LOG_DIR/summary.log"
LIVE_CHECKLIST="$LOG_DIR/live-parity-checklist.md"
CHECKLIST_TEMPLATE="$REPO_ROOT/docs/MACOS_LIVE_PARITY_CHECKLIST.md"
LATEST_LOG_POINTER="$REPO_ROOT/build_logs/latest_macos_phase1.txt"
WISP_APP_BUNDLE_ID="${WISP_APP_BUNDLE_ID:-dev.wisp.native}"
WISP_APP_NAME="${WISP_APP_NAME:-Wisp}"
WISP_APP_VERSION="${WISP_APP_VERSION:-0.1.0}"
WISP_APP_BUILD="${WISP_APP_BUILD:-1}"
mkdir -p "$LOG_DIR"

RUN_MODE="${1:-}"

write_live_checklist() {
  {
    echo "<!-- Generated by scripts/macos_phase1_validate.sh on $RUN_ID. -->"
    echo
    if [ -f "$CHECKLIST_TEMPLATE" ]; then
      cat "$CHECKLIST_TEMPLATE"
    else
      echo "# Native macOS Live Parity Checklist"
      echo
      echo "Checklist template missing: $CHECKLIST_TEMPLATE"
    fi
  } > "$LIVE_CHECKLIST"
}

write_live_checklist

{
  echo "script=scripts/macos_phase1_validate.sh"
  echo "run_id=$RUN_ID"
  echo "log_dir=$LOG_DIR"
  echo "summary_log=$SUMMARY_LOG"
  echo "live_parity_checklist=$LIVE_CHECKLIST"
  echo "log_archive=$ARCHIVE_PATH"
} > "$LATEST_LOG_POINTER"

finish() {
  local status=$?
  echo
  if [ "$status" -eq 0 ]; then
    archive_logs
    echo "Logs written to: $LOG_DIR"
    echo "Live parity checklist: $LIVE_CHECKLIST"
    echo "Latest log pointer: $LATEST_LOG_POINTER"
    [ -f "$ARCHIVE_PATH" ] && echo "Log archive: $ARCHIVE_PATH"
  else
    collect_recent_crash_reports
    archive_logs
    echo "FAILED or crashed with exit code $status."
    echo "Logs written to: $LOG_DIR"
    echo "Live parity checklist: $LIVE_CHECKLIST"
    echo "Latest log pointer: $LATEST_LOG_POINTER"
    [ -f "$ARCHIVE_PATH" ] && echo "Log archive: $ARCHIVE_PATH"
    echo "If macOS generated a crash report, check:"
    echo "  $HOME/Library/Logs/DiagnosticReports"
  fi
}
trap finish EXIT

log_info() {
  echo "$@" | tee -a "$SUMMARY_LOG"
}

run_logged() {
  local name="$1"
  shift
  local log="$LOG_DIR/$name.log"

  log_info "== $name =="
  log_info "command: $*"
  set +e
  "$@" 2>&1 | tee "$log"
  local status=${PIPESTATUS[0]}
  set -e
  if [ "$status" -ne 0 ]; then
    log_info "FAILED: $name (exit $status)"
    return "$status"
  fi
  log_info "PASS: $name"
}

collect_recent_crash_reports() {
  local report_dir="$HOME/Library/Logs/DiagnosticReports"
  local report_log="$LOG_DIR/recent_diagnostic_reports.txt"
  local copies_dir="$LOG_DIR/crash_reports"
  if [ ! -d "$report_dir" ]; then
    return
  fi

  mkdir -p "$copies_dir"
  {
    echo "Recent Wisp/Python/Swift crash reports, newest first:"
    find "$report_dir" -maxdepth 1 -type f \
      \( -name "Wisp*.crash" -o -name "python*.crash" -o -name "python3*.crash" -o -name "swift*.crash" \) \
      -print0 2>/dev/null |
      xargs -0 stat -f "%m|%Sm|%N" -t "%Y-%m-%d %H:%M:%S" 2>/dev/null |
      sort -rn |
      head -20 |
      while IFS="|" read -r _stamp human_time path; do
        echo "$human_time $path"
        cp "$path" "$copies_dir/" 2>/dev/null || true
      done
  } > "$report_log" || true
}

archive_logs() {
  rm -f "$ARCHIVE_PATH"
  if command -v ditto >/dev/null 2>&1; then
    ditto -c -k --keepParent "$LOG_DIR" "$ARCHIVE_PATH" >/dev/null 2>&1 || true
  elif command -v zip >/dev/null 2>&1; then
    (
      cd "$(dirname "$LOG_DIR")"
      zip -qr "$ARCHIVE_PATH" "$(basename "$LOG_DIR")"
    ) || true
  fi
}

plist_escape() {
  local value="$1"
  value="${value//&/&amp;}"
  value="${value//</&lt;}"
  value="${value//>/&gt;}"
  value="${value//\"/&quot;}"
  value="${value//\'/&apos;}"
  printf '%s' "$value"
}

build_dev_app_bundle() {
  local bin_dir app_dir contents_dir macos_dir resources_dir plist executable doll_src doll_dst brain_dst core_dst runtime_dst
  local plist_bundle_id plist_name plist_version plist_build
  bin_dir="$(swift build --show-bin-path 2>"$LOG_DIR/swift-bin-path.err")"
  executable="$bin_dir/Wisp"
  if [ ! -x "$executable" ]; then
    echo "ERROR: Swift executable not found at $executable" >&2
    return 1
  fi

  app_dir="$REPO_ROOT/build/WispNative/Wisp.app"
  contents_dir="$app_dir/Contents"
  macos_dir="$contents_dir/MacOS"
  resources_dir="$contents_dir/Resources"

  rm -rf "$app_dir"
  mkdir -p "$macos_dir" "$resources_dir"
  cp "$executable" "$macos_dir/Wisp"

  brain_dst="$resources_dir/brain"
  core_dst="$resources_dir/core"
  runtime_dst="$resources_dir/python-runtime"
  copy_bundle_source_tree "$REPO_ROOT/macos/brain" "$brain_dst"
  copy_bundle_source_tree "$REPO_ROOT/core" "$core_dst"
  copy_python_runtime_if_requested "$runtime_dst"
  if [ -f "$REPO_ROOT/.env.example" ]; then
    cp "$REPO_ROOT/.env.example" "$resources_dir/.env.example"
  fi
  cat > "$resources_dir/dev-launch.env" <<EOF
WISP_REPO_ROOT=$REPO_ROOT
WISP_BRAIN_PYTHON=$BRAIN_PY
WISP_BRAIN_DIR=$REPO_ROOT/macos/brain
WISP_RUN_LOG_DIR=$LOG_DIR
EOF

  doll_src="$REPO_ROOT/assets/doll"
  doll_dst="$resources_dir/assets/doll"
  if [ -d "$doll_src" ]; then
    mkdir -p "$(dirname "$doll_dst")"
    cp -R "$doll_src" "$doll_dst"
  fi

  plist="$contents_dir/Info.plist"
  plist_bundle_id="$(plist_escape "$WISP_APP_BUNDLE_ID")"
  plist_name="$(plist_escape "$WISP_APP_NAME")"
  plist_version="$(plist_escape "$WISP_APP_VERSION")"
  plist_build="$(plist_escape "$WISP_APP_BUILD")"
  cat > "$plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleDevelopmentRegion</key>
  <string>en</string>
  <key>CFBundleExecutable</key>
  <string>Wisp</string>
  <key>CFBundleIdentifier</key>
  <string>$plist_bundle_id</string>
  <key>CFBundleInfoDictionaryVersion</key>
  <string>6.0</string>
  <key>CFBundleName</key>
  <string>$plist_name</string>
  <key>CFBundlePackageType</key>
  <string>APPL</string>
  <key>CFBundleShortVersionString</key>
  <string>$plist_version</string>
  <key>CFBundleVersion</key>
  <string>$plist_build</string>
  <key>LSMinimumSystemVersion</key>
  <string>13.0</string>
  <key>LSUIElement</key>
  <true/>
  <key>NSAppleEventsUsageDescription</key>
  <string>Wisp may inspect frontmost app context for assistant queries.</string>
  <key>NSMicrophoneUsageDescription</key>
  <string>Wisp records your voice only when you start a voice query.</string>
  <key>NSScreenCaptureUsageDescription</key>
  <string>Wisp captures your screen only when you ask it to include a screenshot.</string>
</dict>
</plist>
PLIST

  {
    echo "app_dir=$app_dir"
    echo "bundle_id=$WISP_APP_BUNDLE_ID"
    echo "bundle_name=$WISP_APP_NAME"
    echo "bundle_version=$WISP_APP_VERSION"
    echo "bundle_build=$WISP_APP_BUILD"
    echo "executable=$macos_dir/Wisp"
    echo "plist=$plist"
    echo "brain_bundle=$brain_dst"
    echo "core_bundle=$core_dst"
    echo "dev_launch_env=$resources_dir/dev-launch.env"
    [ -f "$resources_dir/.env.example" ] && echo "env_template=$resources_dir/.env.example"
    if [ -x "$runtime_dst/bin/python3" ]; then
      echo "python_runtime=$runtime_dst"
      echo "bundle_mode=standalone-shaped"
    else
      echo "python_runtime=(not embedded; set WISP_PYTHON_RUNTIME_DIR to stage one)"
      echo "bundle_mode=checkout-dev"
    fi
    [ -d "$doll_dst" ] && echo "doll_assets=$doll_dst"
  } > "$LOG_DIR/dev-app-bundle.log"

  echo "$macos_dir/Wisp"
}

copy_bundle_source_tree() {
  local src="$1" dst="$2"
  if [ ! -d "$src" ]; then
    echo "ERROR: bundle source directory missing: $src" >&2
    return 1
  fi
  rm -rf "$dst"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$dst"
  find "$dst" \( -name "__pycache__" -o -name ".pytest_cache" \) -type d -prune -exec rm -rf {} +
  find "$dst" \( -name "*.pyc" -o -name "*.pyo" \) -type f -delete
}

copy_python_runtime_if_requested() {
  local dst="$1" src="${WISP_PYTHON_RUNTIME_DIR:-}"
  if [ -z "$src" ]; then
    return 0
  fi
  if [ ! -x "$src/bin/python3" ]; then
    echo "ERROR: WISP_PYTHON_RUNTIME_DIR must contain bin/python3: $src" >&2
    return 1
  fi
  rm -rf "$dst"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$dst"
}

open_dev_app_without_wisp_env() {
  unset WISP_BRAIN_PYTHON WISP_BRAIN_DIR WISP_REPO_ROOT WISP_RUN_LOG_DIR WISP_PYTHON_RUNTIME_DIR
  /usr/bin/open -n "$APP_BUNDLE"
}

quit_existing_wisp_app() {
  local bundle_id
  for bundle_id in "$WISP_APP_BUNDLE_ID" "dev.wisp.native" "com.wisp.native"; do
    /usr/bin/osascript -e "tell application id \"$bundle_id\" to quit" >/dev/null 2>&1 || true
  done
  /usr/bin/pkill -x Wisp >/dev/null 2>&1 || true
  sleep 1
}

validate_dev_launch_env() {
  local resources_dir="$APP_BUNDLE/Contents/Resources"
  local env_file="$resources_dir/dev-launch.env"
  local expected_runtime="$resources_dir/python-runtime/bin/python3"

  if [ ! -f "$env_file" ]; then
    log_info "FAILED: dev launch environment is missing: $env_file"
    return 1
  fi
  if ! grep -Fx "WISP_REPO_ROOT=$REPO_ROOT" "$env_file" >/dev/null; then
    log_info "FAILED: dev launch env has wrong WISP_REPO_ROOT"
    sed 's/^/  /' "$env_file" | tee -a "$SUMMARY_LOG"
    return 1
  fi
  if ! grep -Fx "WISP_BRAIN_PYTHON=$BRAIN_PY" "$env_file" >/dev/null; then
    log_info "FAILED: dev launch env has wrong WISP_BRAIN_PYTHON"
    sed 's/^/  /' "$env_file" | tee -a "$SUMMARY_LOG"
    return 1
  fi
  if ! grep -Fx "WISP_BRAIN_DIR=$REPO_ROOT/macos/brain" "$env_file" >/dev/null; then
    log_info "FAILED: dev launch env has wrong WISP_BRAIN_DIR"
    sed 's/^/  /' "$env_file" | tee -a "$SUMMARY_LOG"
    return 1
  fi
  if ! grep -Fx "WISP_RUN_LOG_DIR=$LOG_DIR" "$env_file" >/dev/null; then
    log_info "FAILED: dev launch env has wrong WISP_RUN_LOG_DIR"
    sed 's/^/  /' "$env_file" | tee -a "$SUMMARY_LOG"
    return 1
  fi
  if [ ! -x "$BRAIN_PY" ]; then
    log_info "FAILED: dev launch Python is not executable: $BRAIN_PY"
    return 1
  fi

  log_info "Dev launch env validated: $env_file"
  sed 's/^/  /' "$env_file" | tee -a "$SUMMARY_LOG"
  if [ -x "$expected_runtime" ]; then
    log_info "Embedded runtime present; marker may resolve brain_python to: $expected_runtime"
  else
    log_info "No embedded runtime present; marker must resolve brain_python to: $BRAIN_PY"
  fi
}

wait_for_open_launch_marker() {
  local marker="$LOG_DIR/native-app-launch.log"
  local resources_dir="$APP_BUNDLE/Contents/Resources"
  local expected_runtime="$resources_dir/python-runtime/bin/python3"
  local expected_python="$BRAIN_PY"
  if [ -x "$expected_runtime" ]; then
    expected_python="$expected_runtime"
  fi
  local i=0
  while [ "$i" -lt 15 ]; do
    if [ -s "$marker" ]; then
      log_info "Native app launch marker detected: $marker"
      sed 's/^/  /' "$marker" | tee -a "$SUMMARY_LOG"
      if ! grep -Fx "brain_python=$expected_python" "$marker" >/dev/null; then
        log_info "FAILED: native app resolved unexpected Python."
        log_info "Expected brain_python=$expected_python"
        return 1
      fi
      if ! grep -Fx "brain_python_exists=true" "$marker" >/dev/null; then
        log_info "FAILED: native app resolved Python path does not exist."
        return 1
      fi
      if ! grep -Fx "brain_python_is_executable=true" "$marker" >/dev/null; then
        log_info "FAILED: native app resolved Python path is not executable."
        return 1
      fi
      if ! grep -Fx "brain_dir_exists=true" "$marker" >/dev/null; then
        log_info "FAILED: native app brain directory does not exist."
        return 1
      fi
      if grep -Fx "brain_python=python" "$marker" >/dev/null || grep -Fx "brain_python_configured=python" "$marker" >/dev/null; then
        log_info "FAILED: native app still resolved or configured bare python."
        return 1
      fi
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done

  log_info "FAILED: native app launch marker was not written within 15 seconds"
  log_info "Expected marker: $marker"
  return 1
}

if [ "$(uname -s 2>/dev/null || true)" != "Darwin" ]; then
  echo "ERROR: this validation script must run on macOS." >&2
  exit 1
fi

if ! command -v swift >/dev/null 2>&1; then
  echo "ERROR: swift was not found. Install Xcode Command Line Tools:" >&2
  echo "       xcode-select --install" >&2
  xcode-select --install >/dev/null 2>&1 || true
  exit 1
fi

WANT="$(tr -d '[:space:]' < .python-version 2>/dev/null || true)"
WANT="${WANT:-3.12.13}"
WANT_MM="$(printf '%s' "$WANT" | cut -d. -f1,2)"
REQ_FILE="$REPO_ROOT/requirements-macos.lock"
STAMP_FILE="$REPO_ROOT/.venv/.wisp-macos-deps.stamp"

if [ ! -f "$REQ_FILE" ]; then
  echo "ERROR: requirements-macos.lock is required for native macOS setup." >&2
  exit 1
fi

python_mm() {
  "$1" -c 'import sys; print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null || true
}

python_matches_want() {
  [ -n "${1:-}" ] && [ "$(python_mm "$1")" = "$WANT_MM" ]
}

try_python() {
  local c="$1" p
  if [ -z "$c" ]; then
    return 1
  fi
  if command -v "$c" >/dev/null 2>&1; then
    p="$(command -v "$c")"
  elif [ -x "$c" ]; then
    p="$c"
  else
    return 1
  fi
  if python_matches_want "$p"; then
    echo "$p"
    return 0
  fi
  return 1
}

find_local_python() {
  local root d c
  root="${PYENV_ROOT:-$HOME/.pyenv}"
  if [ -d "$root/versions" ]; then
    while IFS= read -r d; do
      for c in "$d/bin/python" "$d/bin/python3"; do
        try_python "$c" && return
      done
    done < <(find "$root/versions" -maxdepth 1 -type d -name "$WANT_MM.*" 2>/dev/null | sort -r)
  fi

  for c in "python$WANT_MM" \
           "/Library/Frameworks/Python.framework/Versions/$WANT_MM/bin/python3" \
           "/opt/homebrew/bin/python$WANT_MM" \
           "/usr/local/bin/python$WANT_MM" \
           python3 python; do
    try_python "$c" && return
  done
}

lock_hash() {
  if command -v shasum >/dev/null 2>&1; then
    shasum -a 256 "$REQ_FILE" | awk '{print $1}'
  else
    cksum "$REQ_FILE" | awk '{print $1}'
  fi
}

brain_deps_ok() {
  local py="$1"
  "$py" - <<'PY' >/dev/null 2>&1
import dotenv
import numpy
import soundfile
import faster_whisper
import openai
import anthropic
PY
}

pip_ok() {
  "$1" -m pip --version >/dev/null 2>&1
}

ensure_pip() {
  local py="$1"
  pip_ok "$py" && return 0
  run_logged "python-pip-bootstrap" "$py" -m ensurepip --upgrade
}

venv_ready() {
  [ -x "$REPO_ROOT/.venv/bin/python" ] || return 1
  python_matches_want "$REPO_ROOT/.venv/bin/python" || return 1
  brain_deps_ok "$REPO_ROOT/.venv/bin/python" || return 1
  [ -f "$STAMP_FILE" ] || return 1
  [ "$(cat "$STAMP_FILE" 2>/dev/null || true)" = "$(lock_hash)" ] || return 1
}

ensure_uv() {
  if command -v uv >/dev/null 2>&1; then
    command -v uv
    return 0
  fi
  for c in "$HOME/.local/bin/uv" "$HOME/.cargo/bin/uv"; do
    if [ -x "$c" ]; then
      echo "$c"
      return 0
    fi
  done

  curl -LsSf https://astral.sh/uv/install.sh | sh > "$LOG_DIR/uv-install.log" 2>&1
  for c in "$HOME/.local/bin/uv" "$HOME/.cargo/bin/uv"; do
    if [ -x "$c" ]; then
      echo "$c"
      return 0
    fi
  done
  return 1
}

setup_venv() {
  if venv_ready; then
    BRAIN_PY="$REPO_ROOT/.venv/bin/python"
    log_info "Using existing macOS .venv: $BRAIN_PY"
    return 0
  fi

  if [ "${WISP_SKIP_PIP_INSTALL:-0}" = "1" ] && [ -x "$REPO_ROOT/.venv/bin/python" ]; then
    BRAIN_PY="$REPO_ROOT/.venv/bin/python"
    log_info "Using existing .venv because WISP_SKIP_PIP_INSTALL=1: $BRAIN_PY"
    return 0
  fi

  local py uv
  py="$(find_local_python || true)"
  rm -rf "$REPO_ROOT/.venv"

  if [ -n "$py" ]; then
    log_info "Creating .venv with local Python: $py"
    run_logged "python-venv-create" "$py" -m venv "$REPO_ROOT/.venv"
    BRAIN_PY="$REPO_ROOT/.venv/bin/python"
    ensure_pip "$BRAIN_PY"
    run_logged "python-pip-upgrade" "$BRAIN_PY" -m pip install --upgrade pip
    run_logged "python-deps-install" "$BRAIN_PY" -m pip install -r "$REQ_FILE"
  else
    log_info "Installing/locating uv because Python $WANT was not found locally..."
    uv="$(ensure_uv)"
    if [ -z "$uv" ]; then
      echo "ERROR: could not find/install uv to provision Python $WANT." >&2
      exit 1
    fi
    log_info "Creating .venv with uv Python $WANT"
    run_logged "uv-venv-create" "$uv" venv --python "$WANT" "$REPO_ROOT/.venv"
    BRAIN_PY="$REPO_ROOT/.venv/bin/python"
    run_logged "uv-deps-install" "$uv" pip install --python "$BRAIN_PY" -r "$REQ_FILE"
    ensure_pip "$BRAIN_PY"
  fi

  if ! brain_deps_ok "$BRAIN_PY"; then
    echo "ERROR: installed .venv is still missing native brain dependencies." >&2
    exit 1
  fi
  lock_hash > "$STAMP_FILE"
  log_info "macOS .venv ready: $BRAIN_PY"
}

setup_venv

if [ -z "${BRAIN_PY:-}" ]; then
  echo "ERROR: no Python interpreter found for the brain sidecar." >&2
  exit 1
fi

ensure_pip "$BRAIN_PY"

export WISP_BRAIN_PYTHON="$BRAIN_PY"
export WISP_BRAIN_DIR="$REPO_ROOT/macos/brain"
export WISP_REPO_ROOT="$REPO_ROOT"
export WISP_RUN_LOG_DIR="$LOG_DIR"

{
  echo "repo: $REPO_ROOT"
  echo "run_id: $RUN_ID"
  echo "macOS:"
  sw_vers 2>/dev/null || true
  echo
  echo "swift:"
  swift --version 2>/dev/null || true
  echo
  echo "xcodebuild:"
  xcodebuild -version 2>/dev/null || true
  echo
  echo "python:"
  "$BRAIN_PY" --version 2>&1 || true
  echo "python_path: $BRAIN_PY"
} > "$LOG_DIR/environment.log"

log_info "Log directory: $LOG_DIR"
log_info "Live parity checklist: $LIVE_CHECKLIST"
log_info "Latest log pointer: $LATEST_LOG_POINTER"

# Full brain handler + integration suite when pytest is available; otherwise the
# dependency-free transport test still proves the seam. The suite runs offline
# via the WISP_BRAIN_FAKE_LLM seam, so it needs no API keys or models.
ensure_pytest() {
  "$1" -c "import pytest" >/dev/null 2>&1 && return 0
  "$1" -m pip install pytest >/dev/null 2>&1
}

if ensure_pytest "$BRAIN_PY"; then
  run_logged "python-brain-tests" "$BRAIN_PY" -m pytest macos/brain/tests/ tests/test_config_env.py tests/test_macos_native_validation.py -q
else
  log_info "pytest unavailable; running the transport test directly"
  run_logged "python-brain-sidecar" "$BRAIN_PY" macos/brain/tests/test_brain_host.py
fi

cd macos
run_logged "swift-test" swift test
run_logged "swift-build" swift build
APP_EXECUTABLE="$(build_dev_app_bundle)"
APP_BUNDLE="$(cd "$(dirname "$APP_EXECUTABLE")/../.." && pwd)"
log_info "Dev app bundle ready: $APP_EXECUTABLE"

if [ "$RUN_MODE" = "--run" ]; then
  collect_recent_crash_reports
  run_logged "wisp-app-run" "$APP_EXECUTABLE"
  collect_recent_crash_reports
  exit 0
fi

if [ "$RUN_MODE" = "--open" ]; then
  collect_recent_crash_reports
  validate_dev_launch_env
  quit_existing_wisp_app
  log_info "Launching dev app bundle through macOS open: $APP_BUNDLE"
  log_info "This exercises Finder-style brain/log/resource inference without WISP_BRAIN_* env vars."
  run_logged "wisp-app-open" open_dev_app_without_wisp_env
  wait_for_open_launch_marker
  collect_recent_crash_reports
  echo
  echo "Phase-1 validation passed and Wisp.app launch was requested."
  echo "Use the tray menu or overlay right-click menu to quit Wisp when done."
  exit 0
fi

echo
echo "Phase-1 validation passed. Re-run with --run for terminal logs or --open for Finder-style app launch."
