#!/usr/bin/env bash
# Build, sign, and optionally notarize the native macOS Wisp.app bundle.
#
# Required:
#   WISP_PYTHON_RUNTIME_DIR=/path/to/python-runtime
#   WISP_CODESIGN_IDENTITY="Developer ID Application: ..."
#
# Optional:
#   WISP_CODESIGN_ENTITLEMENTS=macos/Wisp.entitlements
#   WISP_NOTARY_PROFILE=keychain-profile-name
#   WISP_SKIP_NOTARIZATION=1
#   WISP_VALIDATE_APP_LAUNCH=1
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"
RUN_ID="$(date +%Y%m%d-%H%M%S)"
LOG_DIR="$REPO_ROOT/build_logs/macos_package_$RUN_ID"
SUMMARY_LOG="$LOG_DIR/summary.log"
LIVE_CHECKLIST="$LOG_DIR/live-parity-checklist.md"
CHECKLIST_TEMPLATE="$REPO_ROOT/docs/MACOS_LIVE_PARITY_CHECKLIST.md"
LATEST_LOG_POINTER="$REPO_ROOT/build_logs/latest_macos_package.txt"
APP_BUNDLE="$REPO_ROOT/build/WispNative/Wisp.app"
ZIP_PATH="$REPO_ROOT/build/WispNative/Wisp-$RUN_ID.zip"
NOTARY_ZIP_PATH="$REPO_ROOT/build/WispNative/Wisp-notary-submit-$RUN_ID.zip"
LOG_ARCHIVE_PATH="$REPO_ROOT/build_logs/wisp-macos-package-logs_$RUN_ID.zip"
CODESIGN_ENTITLEMENTS="${WISP_CODESIGN_ENTITLEMENTS:-$REPO_ROOT/macos/Wisp.entitlements}"
PACKAGE_BUNDLE_IDENTIFIER="${WISP_BUNDLE_IDENTIFIER:-com.wisp.native}"
PACKAGE_APP_NAME="${WISP_APP_NAME:-Wisp}"
PACKAGE_APP_VERSION="${WISP_APP_VERSION:-0.1.0}"
PACKAGE_APP_BUILD="${WISP_APP_BUILD:-1}"
mkdir -p "$LOG_DIR" "$REPO_ROOT/build/WispNative"

write_live_checklist() {
  {
    echo "<!-- Generated by scripts/macos_package_release.sh on $RUN_ID. -->"
    echo
    if [ -f "$CHECKLIST_TEMPLATE" ]; then
      cat "$CHECKLIST_TEMPLATE"
    else
      echo "# Native macOS Live Parity Checklist"
      echo
      echo "Checklist template missing: $CHECKLIST_TEMPLATE"
    fi
  } > "$LIVE_CHECKLIST"
}

write_live_checklist

{
  echo "script=scripts/macos_package_release.sh"
  echo "run_id=$RUN_ID"
  echo "log_dir=$LOG_DIR"
  echo "summary_log=$SUMMARY_LOG"
  echo "live_parity_checklist=$LIVE_CHECKLIST"
  echo "log_archive=$LOG_ARCHIVE_PATH"
  echo "zip_path=$ZIP_PATH"
  echo "bundle_id=$PACKAGE_BUNDLE_IDENTIFIER"
  echo "bundle_name=$PACKAGE_APP_NAME"
  echo "bundle_version=$PACKAGE_APP_VERSION"
  echo "bundle_build=$PACKAGE_APP_BUILD"
} > "$LATEST_LOG_POINTER"

finish() {
  local status=$?
  echo
  if [ "$status" -ne 0 ]; then
    collect_recent_crash_reports
    echo "FAILED: native macOS package flow exited with $status." | tee -a "$SUMMARY_LOG"
    echo "If macOS generated a crash report, check:" | tee -a "$SUMMARY_LOG"
    echo "  $HOME/Library/Logs/DiagnosticReports" | tee -a "$SUMMARY_LOG"
  fi
  archive_logs
  echo "Logs: $LOG_DIR"
  echo "Live parity checklist: $LIVE_CHECKLIST"
  echo "Latest log pointer: $LATEST_LOG_POINTER"
  [ -f "$LOG_ARCHIVE_PATH" ] && echo "Log archive: $LOG_ARCHIVE_PATH"
}
trap finish EXIT

log_info() {
  echo "$@" | tee -a "$SUMMARY_LOG"
}

run_logged() {
  local name="$1"
  shift
  local log="$LOG_DIR/$name.log"

  log_info "== $name =="
  log_info "command: $*"
  set +e
  "$@" 2>&1 | tee "$log"
  local status=${PIPESTATUS[0]}
  set -e
  if [ "$status" -ne 0 ]; then
    log_info "FAILED: $name (exit $status)"
    return "$status"
  fi
  log_info "PASS: $name"
}

collect_recent_crash_reports() {
  local report_dir="$HOME/Library/Logs/DiagnosticReports"
  local report_log="$LOG_DIR/recent_diagnostic_reports.txt"
  local copies_dir="$LOG_DIR/crash_reports"
  if [ ! -d "$report_dir" ]; then
    return
  fi

  mkdir -p "$copies_dir"
  {
    echo "Recent Wisp/Python/Swift crash reports, newest first:"
    find "$report_dir" -maxdepth 1 -type f \
      \( -name "Wisp*.crash" -o -name "python*.crash" -o -name "python3*.crash" -o -name "swift*.crash" \) \
      -print0 2>/dev/null |
      xargs -0 stat -f "%m|%Sm|%N" -t "%Y-%m-%d %H:%M:%S" 2>/dev/null |
      sort -rn |
      head -20 |
      while IFS="|" read -r _stamp human_time path; do
        echo "$human_time $path"
        cp "$path" "$copies_dir/" 2>/dev/null || true
      done
  } > "$report_log" || true
}

archive_logs() {
  rm -f "$LOG_ARCHIVE_PATH"
  if command -v ditto >/dev/null 2>&1; then
    ditto -c -k --keepParent "$LOG_DIR" "$LOG_ARCHIVE_PATH" >/dev/null 2>&1 || true
  elif command -v zip >/dev/null 2>&1; then
    (
      cd "$(dirname "$LOG_DIR")"
      zip -qr "$LOG_ARCHIVE_PATH" "$(basename "$LOG_DIR")"
    ) || true
  fi
}

require_macos_tools() {
  if [ "$(uname -s 2>/dev/null || true)" != "Darwin" ]; then
    echo "ERROR: this packaging script must run on macOS." >&2
    exit 1
  fi
  for tool in codesign ditto spctl xcrun; do
    if ! command -v "$tool" >/dev/null 2>&1; then
      echo "ERROR: required macOS packaging tool not found: $tool" >&2
      exit 1
    fi
  done
}

require_inputs() {
  if [ -z "${WISP_PYTHON_RUNTIME_DIR:-}" ]; then
    echo "ERROR: WISP_PYTHON_RUNTIME_DIR is required for a release-shaped package." >&2
    exit 1
  fi
  if [ ! -x "$WISP_PYTHON_RUNTIME_DIR/bin/python3" ]; then
    echo "ERROR: WISP_PYTHON_RUNTIME_DIR must contain bin/python3: $WISP_PYTHON_RUNTIME_DIR" >&2
    exit 1
  fi
  if [ -z "${WISP_CODESIGN_IDENTITY:-}" ]; then
    echo "ERROR: WISP_CODESIGN_IDENTITY is required, for example:" >&2
    echo "       WISP_CODESIGN_IDENTITY='Developer ID Application: Your Name (TEAMID)'" >&2
    exit 1
  fi
  if [ ! -f "$CODESIGN_ENTITLEMENTS" ]; then
    echo "ERROR: codesign entitlements file not found: $CODESIGN_ENTITLEMENTS" >&2
    exit 1
  fi
}

build_release_shaped_bundle() {
  log_info "Building release-shaped Wisp.app with embedded runtime..."
  WISP_APP_BUNDLE_ID="$PACKAGE_BUNDLE_IDENTIFIER" \
  WISP_APP_NAME="$PACKAGE_APP_NAME" \
  WISP_APP_VERSION="$PACKAGE_APP_VERSION" \
  WISP_APP_BUILD="$PACKAGE_APP_BUILD" \
  WISP_PYTHON_RUNTIME_DIR="$WISP_PYTHON_RUNTIME_DIR" \
    /bin/bash scripts/macos_phase1_validate.sh | tee "$LOG_DIR/phase1.log"

  if [ ! -d "$APP_BUNDLE" ]; then
    echo "ERROR: expected app bundle was not built: $APP_BUNDLE" >&2
    exit 1
  fi
  if [ ! -x "$APP_BUNDLE/Contents/Resources/python-runtime/bin/python3" ]; then
    echo "ERROR: app bundle is missing embedded python-runtime/bin/python3." >&2
    exit 1
  fi
  rm -f "$APP_BUNDLE/Contents/Resources/dev-launch.env"
  log_info "Removed dev launch environment from release bundle."
}

validate_bundle_metadata() {
  local plist="$APP_BUNDLE/Contents/Info.plist"
  if [ ! -f "$plist" ]; then
    echo "ERROR: app bundle is missing Info.plist: $plist" >&2
    exit 1
  fi
  if ! grep -A1 "<key>CFBundleIdentifier</key>" "$plist" | grep -Fx "  <string>$PACKAGE_BUNDLE_IDENTIFIER</string>" >/dev/null; then
    echo "ERROR: packaged app has unexpected CFBundleIdentifier." >&2
    echo "Expected: $PACKAGE_BUNDLE_IDENTIFIER" >&2
    exit 1
  fi
  if [ "$PACKAGE_BUNDLE_IDENTIFIER" = "dev.wisp.native" ]; then
    echo "ERROR: release package must not use the dev bundle identifier dev.wisp.native." >&2
    echo "Set WISP_BUNDLE_IDENTIFIER to your release reverse-DNS app id." >&2
    exit 1
  fi
  log_info "Bundle identifier: $PACKAGE_BUNDLE_IDENTIFIER"
  log_info "Bundle version: $PACKAGE_APP_VERSION ($PACKAGE_APP_BUILD)"
}

validate_embedded_python() {
  local resources="$APP_BUNDLE/Contents/Resources"
  local py="$resources/python-runtime/bin/python3"
  local probe="$LOG_DIR/embedded_python_probe.py"

  cat > "$probe" <<'PY'
from __future__ import annotations

import importlib
import sys

required = [
    "wisp_brain.host",
    "wisp_brain.handlers",
    "core.llm_clients.client",
    "dotenv",
    "numpy",
    "soundfile",
    "faster_whisper",
    "openai",
    "anthropic",
]

failed: list[tuple[str, str]] = []
for name in required:
    try:
        importlib.import_module(name)
    except Exception as exc:  # noqa: BLE001 - packaging probe reports all failures.
        failed.append((name, f"{type(exc).__name__}: {exc}"))

if failed:
    print("Embedded Python import probe failed:", file=sys.stderr)
    for name, message in failed:
        print(f"  {name}: {message}", file=sys.stderr)
    raise SystemExit(1)

print("Embedded Python import probe passed.")
PY

  run_logged "embedded-python-imports" /usr/bin/env \
    "PYTHONPATH=$resources:$resources/brain${PYTHONPATH:+:$PYTHONPATH}" \
    "$py" "$probe"
}

sign_bundle() {
  log_info "Codesign entitlements: $CODESIGN_ENTITLEMENTS"
  run_logged "codesign-app" \
    codesign --force --deep --options runtime --timestamp \
      --entitlements "$CODESIGN_ENTITLEMENTS" \
      --sign "$WISP_CODESIGN_IDENTITY" "$APP_BUNDLE"
  run_logged "codesign-verify" codesign --verify --deep --strict --verbose=2 "$APP_BUNDLE"
  run_logged "codesign-entitlements" codesign -d --entitlements :- "$APP_BUNDLE"
}

zip_app() {
  local name="$1" output="$2"
  rm -f "$output"
  run_logged "$name" ditto -c -k --keepParent "$APP_BUNDLE" "$output"
  log_info "Zip: $output"
}

notarize_if_requested() {
  if [ "${WISP_SKIP_NOTARIZATION:-0}" = "1" ]; then
    log_info "Skipping notarization because WISP_SKIP_NOTARIZATION=1."
    log_info "Gatekeeper assessment is skipped because the app is not notarized."
    return 0
  fi
  if [ -z "${WISP_NOTARY_PROFILE:-}" ]; then
    echo "ERROR: WISP_NOTARY_PROFILE is required unless WISP_SKIP_NOTARIZATION=1." >&2
    echo "       Create one with: xcrun notarytool store-credentials <profile-name>" >&2
    exit 1
  fi

  zip_app "zip-notary-submit" "$NOTARY_ZIP_PATH"
  run_logged "notary-submit" \
    xcrun notarytool submit "$NOTARY_ZIP_PATH" --keychain-profile "$WISP_NOTARY_PROFILE" --wait
  run_logged "staple-app" xcrun stapler staple "$APP_BUNDLE"
  run_logged "spctl-assess-stapled" spctl --assess --type execute --verbose "$APP_BUNDLE"
  zip_app "zip-stapled-app" "$ZIP_PATH"
}

open_signed_app_without_wisp_env() {
  local bundle="${1:-$APP_BUNDLE}"
  (
    unset WISP_BRAIN_PYTHON
    unset WISP_BRAIN_DIR
    unset WISP_REPO_ROOT
    unset WISP_RUN_LOG_DIR
    unset WISP_PYTHON_RUNTIME_DIR
    unset WISP_VALIDATE_APP_LAUNCH
    /usr/bin/open -n "$bundle"
  )
}

quit_existing_wisp_app() {
  local bundle_id
  for bundle_id in "$PACKAGE_BUNDLE_IDENTIFIER" "dev.wisp.native" "com.wisp.native"; do
    /usr/bin/osascript -e "tell application id \"$bundle_id\" to quit" >/dev/null 2>&1 || true
  done
  /usr/bin/pkill -x Wisp >/dev/null 2>&1 || true
  sleep 1
}

validate_signed_app_launch_if_requested() {
  if [ "${WISP_VALIDATE_APP_LAUNCH:-0}" != "1" ]; then
    return 0
  fi

  local app_marker="$HOME/Library/Logs/Wisp/native-app-launch.log"
  local marker="$LOG_DIR/native-app-launch.log"
  local launch_root="${TMPDIR:-/tmp}/wisp-signed-launch-$RUN_ID"
  local launch_app="$launch_root/Wisp.app"
  local expected_python="$launch_app/Contents/Resources/python-runtime/bin/python3"
  rm -f "$app_marker" "$marker"
  rm -rf "$launch_root"
  mkdir -p "$launch_root"
  run_logged "copy-signed-app-for-launch" ditto "$APP_BUNDLE" "$launch_app"
  run_logged "codesign-verify-launch-copy" codesign --verify --deep --strict --verbose=2 "$launch_app"
  if [ ! -x "$expected_python" ]; then
    log_info "FAILED: launch-validation app copy is missing embedded Python."
    log_info "Expected python: $expected_python"
    return 1
  fi
  if [ -f "$launch_app/Contents/Resources/dev-launch.env" ]; then
    log_info "FAILED: launch-validation app copy still contains dev-launch.env."
    return 1
  fi

  quit_existing_wisp_app

  log_info "Launching signed Wisp.app for native startup validation..."
  log_info "Launch validation app copy: $launch_app"
  log_info "This launch clears WISP_* dev/test variables before calling open."
  run_logged "signed-app-open" open_signed_app_without_wisp_env "$launch_app"

  local i=0
  while [ "$i" -lt 20 ]; do
    if [ -s "$app_marker" ]; then
      if ! cp "$app_marker" "$marker" 2>/dev/null; then
        log_info "FAILED: could not copy signed app launch marker into package log folder."
        log_info "Source marker: $app_marker"
        log_info "Destination marker: $marker"
        quit_existing_wisp_app
        return 1
      fi
      log_info "Signed app launch marker detected: $app_marker"
      log_info "Copied launch marker to package log evidence: $marker"
      sed 's/^/  /' "$marker" | tee -a "$SUMMARY_LOG"
      if ! grep -Fx "brain_python=$expected_python" "$marker" >/dev/null; then
        log_info "FAILED: signed app resolved unexpected Python."
        log_info "Expected brain_python=$expected_python"
        quit_existing_wisp_app
        return 1
      fi
      if ! grep -Fx "brain_python_exists=true" "$marker" >/dev/null; then
        log_info "FAILED: signed app resolved Python path does not exist."
        quit_existing_wisp_app
        return 1
      fi
      if ! grep -Fx "brain_python_is_executable=true" "$marker" >/dev/null; then
        log_info "FAILED: signed app resolved Python path is not executable."
        quit_existing_wisp_app
        return 1
      fi
      if ! grep -Fx "brain_dir_exists=true" "$marker" >/dev/null; then
        log_info "FAILED: signed app brain directory does not exist."
        quit_existing_wisp_app
        return 1
      fi
      if grep -Fx "brain_python=python" "$marker" >/dev/null || grep -Fx "brain_python_configured=python" "$marker" >/dev/null; then
        log_info "FAILED: signed app still resolved or configured bare python."
        quit_existing_wisp_app
        return 1
      fi
      quit_existing_wisp_app
      return 0
    fi
    i=$((i + 1))
    sleep 1
  done

  log_info "FAILED: signed app launch marker was not written within 20 seconds"
  log_info "Expected marker: $app_marker"
  log_info "If Wisp is still running, quit it from the tray menu before rerunning packaging."
  return 1
}

require_macos_tools
require_inputs
log_info "Live parity checklist: $LIVE_CHECKLIST"
log_info "Latest log pointer: $LATEST_LOG_POINTER"
build_release_shaped_bundle
validate_bundle_metadata
validate_embedded_python
sign_bundle
notarize_if_requested
if [ "${WISP_SKIP_NOTARIZATION:-0}" = "1" ]; then
  zip_app "zip-signed-app" "$ZIP_PATH"
fi
validate_signed_app_launch_if_requested

log_info "Native macOS package flow completed."
log_info "Final zip: $ZIP_PATH"
log_info "Logs: $LOG_DIR"
